### ISSUE TITLE
1-2_show more information at list items

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#24]
## Value Proposition

**As a** user 

**I need** to see a detailed information of sport locations

**to be able to** better choose a place where I can do sport

## Description

![11-show more info at list items](https://user-images.githubusercontent.com/115343305/206899900-09814100-a0dc-434c-a813-eeab77666830.png)

## Acceptance Criteria

- [x] show list items with more information of sport locations
         [title, tags, rating, address, image url]

## Tasks

(for developers team)

- [x] update dummy array for locations with more information [title, tags, rating, address, image url]
    max. 2 tags, address showing city or district only
- [x] insert example pictures from unsplash
- [x] use styledComponents 
- [x] create pull request
