### ISSUE TITLE
1-3_show single page when click on entry

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#25]
## Value Proposition

**As a** user 

**I want to** see a detailed information of sport locations after clicked on list item

**to be able to** get more information about the place where I think about to go to

## Description

![12-show single page when click on entry](https://user-images.githubusercontent.com/115343305/207088027-70dd28e5-7682-4855-b9db-e15c9cf06234.png)

## Acceptance Criteria

- [x] show single page of sport location with more information available
     [image, title, description, rating, address, tags, opening times]
- [x] use dynamic routing (e.g. [slug].js)
- [x] page is scrollable in y-direction
- [x] "go back" -button

## Tasks

(for developers team)

- [x] update dummy array for locations with more information [...dummyarray, description, opening times]
- [x] add a "go back" button
- [x] dummy array is located in lib folder
- [x] page is aligned into grid
- [x] create pull request
