### ISSUE TITLE
1-4-filter and sort list items

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#26]
## Value Proposition

**As a** user 

**I need** to filter and sort list items

**to be able to** faster choose a place where I can do sport

## Description

![13-filter and sort list items](https://user-images.githubusercontent.com/115343305/207089872-d71f5939-0811-45ea-9d5e-f97a3bce59c4.png)

## Acceptance Criteria

- [x] filter list items by
         [kind of sport, city, tags, rating,]
- [x] sort list items by
    [alphabetically]
- [x] filter and sort can be applied together
- [x] multiple filters can be use simultaneously
- [x] only render items that meet filter  criteria

## Tasks

(for developers team)

- [x] use array methods to filter and sort
- [x] add dropdown with checkbox for filter selection
- [x] add dropdown menu for sort
- [x] create pull request
