### ISSUE TITLE
2-5-add favorite button

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#27]
## Value Proposition

**As a** user 

**I want** to mark a list item as favorite

**to be able to** note places that I visit frequently

## Description

![14-add favorite button](https://user-images.githubusercontent.com/115343305/206919779-c96d9d1a-5794-486e-8c81-053392f77a5f.png)
![14-add favorite button-2](https://user-images.githubusercontent.com/115343305/207090750-441fe5ca-5958-410e-b4ab-4d739053a82a.png)

## Acceptance Criteria

- [x] favorite button on list item
- [x] favorite button on details page
- [x] favorite button is clickable and changes style when checked

## Tasks

(for developers team)

- [x] add favorite button on list item
- [x] add favorite button on details page
- [x] make button a component and use it on list item and details page
- [x] change style when checked
- [x] update state when checked
- [x] create pull request
