### ISSUE TITLE
2-6-add favorites page and navbar

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#28]
## Value Proposition

**As a** user 

**I want** to see my favorites only

**to be able to** get an overview of places that I visit frequently

## Description

![15-add favorite page and navbar](https://user-images.githubusercontent.com/115343305/206920303-35533de6-4d0d-4279-9ee3-8910ecd5cb13.png)

## Acceptance Criteria

- [x] show list items marked as favorite on separate page
- [x] navbar on the bottom
- [x] home redirects to complete list
- [x] style of active icon changes

## Tasks

(for developers team)

- [x] render separate page that show favorite list items only
- [x] add navbar on bottom
- [x] create navbar as a component
- [x] migrate navbar in global styled (mobile layout grid)
- [x] add button for complete list and favorite list
- [x] create pull request
