### ISSUE TITLE
2-7-add share button

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#30]
## Value Proposition

**As a** user 

**I want** to share a sport location

**to be able to** share nice locations with my friends

## Description

![Image](https://user-images.githubusercontent.com/115343305/208614168-f9b5c1ee-2223-487f-b6ad-27e4f3125386.png)

## Acceptance Criteria

- [x] render share button on details page
- [x] open share dialog on mobile device

## Tasks

(for developers team)

- [x] add button on details page
- [x] use navigator.share to open share dialog
- [x] copy link to clipboard if browser does not support native share dialog
- [x] show message "copied to clip board" when copied to clip board
- [x] create pull request
