### ISSUE TITLE
2-8-form to add new location

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#31]
## Value Proposition

**As a** user 

**I want** to add a new sport location to my library

**to be able to** share sport locations with the world.

## Description

![28-add form](https://user-images.githubusercontent.com/115343305/208511442-891893c5-cd32-4f9d-a717-94eaefbd4b3f.png)

## Acceptance Criteria

- [x] add "add entry" button to navbar
- [x] render form where you can enter information (title, address, description, tags, category, rating)
- [x] add submit button

## Tasks

(for developers team)

- [x] route to a new created page that renders the form
- [x] set title, category, rating and address as required
- [x] rating must be number
- [x] title has max. 50 characters
- [x] a random unsplash foto will be chosen based on category / or a default illustration as placeholder (image upload will be added later, for now a default picture is used)
- [ ] create pull request
