### ISSUE TITLE
2-10_setup and connect database

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#33]
## Value Proposition

**As a** developer 
**I want to** setup and connect a database
**so that** the data is stored in a database and the app fetches data to ensure that all users have access to new uploaded data
​

## Description

A fully integrated MongoDB to replace sportLocationsData Array saved in lib/data.

## Acceptance Criteria

- [x] database must be deployed remote on Vercel that every user has access 
- [x] use mongoDB

## Tasks

(for developers team)

- [x] setup a new mongoDB and collection
- [x] install mongoose
- [x]  create schema and add dbConnect.js
- [x] enter environment variables on Vercel
- [x] write API that handles request and response with database
- [x] replace all the refers in the code from the old "sportLocationsData.js" file to the new database
- [x] create pull request
