### ISSUE TITLE
3-16_show card when click on marker

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#39]
## Value Proposition

**As a** user 

**I want to** click on a marker in the map

**to be able to** to see what is at this location

## Description

![3-16_show card preview](https://user-images.githubusercontent.com/115343305/211297337-463c1e09-acbd-4c1c-a5d3-4a5a705b61d1.png)

## Acceptance Criteria

- [ ] after clicking on a marker a popup window should appear
- [ ] clicking on that window should route to the details page
- [ ] popup window should disappear when clicking somewhere else on the map

## Tasks

(for developers team)

- [ ] add popup window
- [ ] add route to details page
- [ ] create pull request
