### ISSUE TITLE
4-18_add image upload to new entry formular

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone-project-ts#40]
## Value Proposition

**As a** user 

**I want** to add images to a new sport location

**to be able to** to get better impression how the sport location looks like.

## Description

![4-18_add image upload](https://user-images.githubusercontent.com/115343305/212718992-f5c7adc4-9dd6-4206-810b-d75ce7fd7728.png)

## Acceptance Criteria

- [x] add image upload button
- [x] if no image uploaded use a default picture 

## Tasks
(for developers team)

- [x] install cloudinary package
- [x] store uploaded images on cloudinary
- [x] show confirmation that the image is successfully uploaded and error message if not
- [x] file upload must be before form submit
- [x] create pull request
